check that report has been generated

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -30,6 +30,14 @@ jobs:
         continue-on-error: true
         run: ./test_modeling_interface --reporter xml -o test_modeling_interface.xml
 
+      - name: Check report has been created
+        working-directory: ${{github.workspace}}/build/tests/mixed-integer/modeling
+        run: |
+          if [ ! -f test_modeling_interface.xml ]; then
+            echo "Test report not found!"
+            exit 1
+          fi
+
       - name: Build coverage report
         run: lcov --directory . --capture --output-file coverage__${{ github.job }}__${{ github.run_id }}.info
 
@@ -156,6 +164,13 @@ jobs:
           fi
           
           (cd $WORKSPACE && (./test_wrapper_${OPTIMIZER} --reporter xml -o test_wrapper_${OPTIMIZER}.xml ) )
+
+      - name: Check report has been created
+        run: |
+          if [ ! -f $WORKSPACE/test_wrapper_${OPTIMIZER}.xml ]; then
+            echo "Test report not found!"
+            exit 1
+          fi
 
       - name: Build coverage report
         run: lcov --directory . --capture --output-file coverage__${{ github.job }}__${{ github.run_id }}.info
